# Generated by Django 5.1.3 on 2024-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(default='без опыта', max_length=255, verbose_name='Опыт работы'),
        ),
    ]
