# Generated by Django 5.1.3 on 2024-11-10 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0002_alter_job_company_alter_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_ad',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
