# Generated by Django 5.1.3 on 2024-11-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_app', '0003_job_created_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
